[build]
  publish = "dist"
  command = "npm install && npm run build"

[dev]
  command = "npm run dev"
  port = 8888        # Netlify Dev listens on this port
  targetPort = 3000  # Vite runs on this port
  framework = "#custom"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "16"
  NPM_FLAGS = "--no-audit --no-fund"